name: EVCS Data Scraper (Simple - No selenium-wire)

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger
    inputs:
      send_email:
        description: 'Send email notification'
        required: false
        default: true
        type: boolean

jobs:
  scrape-evcs-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        
    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-driver
        chromedriver --version
        
    - name: Install Python dependencies (Simple - No selenium-wire)
      run: |
        python -m pip install --upgrade pip
        # Only install essential packages - no selenium-wire
        pip install selenium==4.15.2
        pip install pandas==2.1.3
        pip install openpyxl==3.1.2
        pip install sib-api-v3-sdk==7.6.0
        pip install python-dotenv==1.0.0
        
    - name: Create .env file from secrets
      run: |
        echo "EMAIL_API_KEY=${{ secrets.EMAIL_API_KEY }}" > .env
        echo "NOTIFICATION_EMAIL=${{ secrets.NOTIFICATION_EMAIL }}" >> .env
        
    - name: Run EVCS scraper (Simple version)
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        python evcs_scraper_simple.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: evcs-data-simple-${{ github.run_number }}
        path: |
          evcs_data_*.json
          evcs_data_*.xlsx
          evcs_data_*.csv
        retention-days: 30
